# Generated by Django 3.1.1 on 2020-09-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0002_auto_20200916_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Id пользователя в соц сети'),
        ),
    ]
