# Generated by Django 3.1.1 on 2020-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0003_auto_20200916_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numquestion',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер вопроса'),
        ),
    ]
