# Generated by Django 3.1.1 on 2020-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0004_profile_numquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalNumQuestion', models.PositiveIntegerField(verbose_name='Номер вопроса')),
                ('textQuestion', models.TextField(verbose_name='Текст вопроса')),
                ('typeOfAnswer', models.TextField(verbose_name='Тип ответа')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
