# Generated by Django 3.1.1 on 2020-09-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0006_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typeOfQuestion',
            field=models.TextField(default='Вебинар', verbose_name='Тип задаваемых вопросов'),
        ),
    ]
