# Generated by Django 3.1.1 on 2020-09-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0007_profile_typeofquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='respondentId',
            field=models.PositiveIntegerField(verbose_name='Id ответчика'),
        ),
    ]
