# Generated by Django 3.1.1 on 2020-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0009_profile_numoffiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='numAnswer',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер ответа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numquestion',
            field=models.IntegerField(default=-1, verbose_name='Номер вопроса'),
        ),
    ]
