# Generated by Django 3.1.1 on 2020-09-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0011_auto_20200927_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='numAnswer',
            field=models.TextField(default=0, verbose_name='Номер ответа'),
        ),
    ]
