# Generated by Django 3.1.1 on 2020-10-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0012_auto_20200927_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinarTitle', models.TextField(verbose_name='Название вебинара')),
                ('webinarID', models.PositiveIntegerField(verbose_name='Идентификатор Вебинара')),
                ('webinarDate', models.DateField(verbose_name='Дата вебинара')),
                ('webinarTime', models.TimeField(verbose_name='Дата вебинара')),
            ],
            options={
                'verbose_name': 'Вебинар',
                'verbose_name_plural': 'Вебинары',
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
