# Generated by Django 3.1.1 on 2020-10-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0013_auto_20201016_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.PositiveIntegerField(verbose_name='ID')),
                ('userWebinar', models.TextField(verbose_name='ID Вебинара')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='numOfFiles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='numquestion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='typeOfQuestion',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
