# Generated by Django 3.1.1 on 2020-10-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0014_auto_20201016_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='webinarDescription',
            field=models.TextField(default=0, verbose_name='Описание Вебинара'),
            preserve_default=False,
        ),
    ]
