# Generated by Django 3.1.1 on 2020-10-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0015_webinars_webinardescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinars',
            name='webinarDescription',
            field=models.TextField(default=0, verbose_name='Описание Вебинара'),
        ),
    ]
