# Generated by Django 3.1.1 on 2020-10-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0016_auto_20201016_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='webinarIDRegister',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Id выбранного вебинара'),
            preserve_default=False,
        ),
    ]
