# Generated by Django 3.1.1 on 2020-10-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0017_profile_webinaridregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userQuestion',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер вопроса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registers',
            name='userMail',
            field=models.TextField(default=0, verbose_name='Почта пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registers',
            name='userName',
            field=models.TextField(default=0, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registers',
            name='userNum',
            field=models.TextField(default=0, verbose_name='Телефон пользователя'),
            preserve_default=False,
        ),
    ]
