# Generated by Django 3.1.1 on 2020-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0019_auto_20201016_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userQuestion',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер вопроса'),
        ),
    ]
