# Generated by Django 3.1.1 on 2020-10-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0020_auto_20201022_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userQuestion',
            field=models.PositiveIntegerField(verbose_name='Номер вопроса'),
        ),
    ]
