# Generated by Django 3.1.1 on 2020-10-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0022_auto_20201022_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='userID',
            field=models.PositiveIntegerField(verbose_name='ID'),
        ),
    ]
