# Generated by Django 3.1.1 on 2020-10-22 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0023_auto_20201022_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinars',
            name='webinarDate',
        ),
        migrations.RemoveField(
            model_name='webinars',
            name='webinarTime',
        ),
        migrations.AddField(
            model_name='webinars',
            name='webinarDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время вебинара'),
            preserve_default=False,
        ),
    ]
