# Generated by Django 3.1.1 on 2020-10-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0024_auto_20201022_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='webinarIDRegister',
            field=models.PositiveIntegerField(default=0, verbose_name='Id выбранного вебинара'),
        ),
    ]
