# Generated by Django 3.1.1 on 2020-10-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0025_auto_20201023_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.TextField(verbose_name='Название видео')),
                ('videoUrl', models.TextField(verbose_name='Ссылка на видео')),
                ('videoDescription', models.TextField(verbose_name='Описание видео')),
            ],
        ),
    ]
