# Generated by Django 3.1.1 on 2020-10-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0026_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='videoID',
            field=models.TextField(default='Не определено', verbose_name='ID видео'),
        ),
    ]
