# Generated by Django 3.1.1 on 2020-10-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0027_videos_videoid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='videos',
            name='videoAdminDescription',
            field=models.TextField(default=123, verbose_name='Системное описание видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videos',
            name='videoID',
            field=models.PositiveIntegerField(default=0, verbose_name='ID видео'),
        ),
    ]
