# Generated by Django 3.1.1 on 2020-10-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0028_auto_20201026_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='userStatus',
            field=models.TextField(default='Нет', verbose_name='Статус'),
        ),
    ]
