# Generated by Django 3.1.1 on 2020-10-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0029_registers_userstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webinars',
            new_name='WebinarsDjango',
        ),
    ]
