# Generated by Django 3.1.1 on 2020-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0031_profile_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarsdjango',
            name='webinarUrl',
            field=models.TextField(default=0, verbose_name='Ссылка на вебинар'),
        ),
    ]
