# Generated by Django 3.1.1 on 2020-10-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0033_auto_20201031_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarsdjango',
            name='webinarID',
            field=models.PositiveIntegerField(verbose_name='Идентификатор Вебинара'),
        ),
    ]
