# Generated by Django 3.1.1 on 2020-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0034_auto_20201031_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='numOfNotWebinar',
            field=models.IntegerField(default=0, verbose_name='Счетчик'),
        ),
    ]
