# Generated by Django 3.1.1 on 2020-11-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0035_registers_numofnotwebinar'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='userReason',
            field=models.TextField(default='Нет', verbose_name='Причина'),
        ),
    ]
