# Generated by Django 3.1.1 on 2020-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0036_registers_userreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileNum',
            field=models.TextField(default=0, verbose_name='Телефон поьзователя'),
        ),
    ]
