# Generated by Django 3.1.1 on 2020-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0037_profile_profilenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarsdjango',
            name='webinarDescription2',
            field=models.TextField(default=0, verbose_name='Описание Вебинара2'),
        ),
        migrations.AddField(
            model_name='webinarsdjango',
            name='webinarDescription3',
            field=models.TextField(default=0, verbose_name='Описание Вебинара3'),
        ),
    ]
