# Generated by Django 3.1.1 on 2020-11-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0039_auto_20201120_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(blank=True, default=0, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='userQuestion',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер вопроса'),
        ),
    ]
