# Generated by Django 3.1.1 on 2020-12-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0040_auto_20201120_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='user_know_impact',
            field=models.TextField(default='Не определено', verbose_name='Знает ли о компании?'),
        ),
        migrations.AddField(
            model_name='registers',
            name='user_know_investion',
            field=models.TextField(default='Не определено', verbose_name='Знает ли о инвестициях?'),
        ),
        migrations.AddField(
            model_name='registers',
            name='user_who_know_impact',
            field=models.TextField(default='Нет', verbose_name='Откуда знает'),
        ),
        migrations.AddField(
            model_name='registers',
            name='user_who_know_investion_currently',
            field=models.TextField(default='Нет', verbose_name='О каких именно'),
        ),
    ]
