# Generated by Django 3.1.1 on 2020-12-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0041_auto_20201204_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default='Нет', verbose_name='Имя пользователя'),
        ),
    ]
