# Generated by Django 3.1.1 on 2020-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0042_auto_20201205_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarsdjango',
            name='webinarVideoUrl',
            field=models.TextField(default='0', verbose_name='Ссылка на запись'),
        ),
    ]
