# Generated by Django 3.1.1 on 2020-12-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0044_auto_20201212_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegramIdLink', models.TextField(verbose_name='id для телеграмма')),
                ('utm_source', models.TextField(verbose_name='utm_source')),
                ('utm_medium', models.TextField(verbose_name='utm_medium')),
                ('utm_campaign', models.TextField(verbose_name='utm_campaign')),
                ('utm_content', models.TextField(verbose_name='utm_content')),
                ('utm_term', models.TextField(verbose_name='utm_term')),
                ('roistat_visit', models.TextField(blank=True, verbose_name='roistat_visit')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='user_tg_parameteres_id',
            field=models.TextField(blank=True, verbose_name='ID для Tg'),
        ),
    ]
