# Generated by Django 3.1.1 on 2020-12-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs', '0045_auto_20201213_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='utm_campaign',
            field=models.TextField(blank=True, verbose_name='utm_campaign'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='utm_content',
            field=models.TextField(blank=True, verbose_name='utm_content'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='utm_medium',
            field=models.TextField(blank=True, verbose_name='utm_medium'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='utm_source',
            field=models.TextField(blank=True, verbose_name='utm_source'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='utm_term',
            field=models.TextField(blank=True, verbose_name='utm_term'),
        ),
    ]
